handler:
  host : localhost
  port : 9082
storage-handler:
  host : localhost
  port : 9083
clerk:
  host : localhost
  port : 9086
s3-temp-storage:
  type: s3
  name: temp_switch_ch
  key: AKIAFEDBDB2704C24D21
  bucket: ub-test_dlza-temporary
  api-url-value: https://vip-ecs-ub.storage.p.unibas.ch
  url: vip-ecs-ub.storage.p.unibas.ch
  upload-folder: vfs:/temp_switch_ch
  capem: "ignore"
  debug: false

#modify if needed the hosts/ports