#localaddr = ":8789"
localaddr = ":0"
#domains = ["ubmedia", "mediathek"]
domain = "ubdlza"
bearer = "grmbl"
resolveraddr = "[::1]:7777"
#resolveraddr = "127.0.0.1:7777"
resolvertimeout = "10m"
actiontimeout = "15m"
resolvernotfoundtimeout = "10s"
externaladdr = "https://localhost:8765"

#[grpcclient]
#mediaserverdb = "localhost:7653"

[server]
type = "minivault"
initialtimeout = "1h"
[server.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.222544d8828687bf.2ea79c2f20d1c5ea" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "server_cert"
tokenpolicies = ["ubdlza.storagehandler"]
tokeninterval = "48h"
tokenttl = "96h"
certtype = "server_cert"
dnss = ["ubdlza.storagehandlerproto.DispatcherStorageHandlerService", "ubdlza.storagehandlerproto.CheckerStorageHandlerService"]#, "ubdlza.storagehandlerproto.ClerkStorageHandlerService"
uris = []
ips = []
certinterval = "36h"
certttl = "48h"
ca = ["certs/minivault.ca.pem"]
usesystempool = false


[client]
type = "minivault"
initialtimeout = "1h"
[client.minivault]
baseurl = "https://localhost:8759/api/v1"
parenttoken = "pa.222544d8828687bf.2ea79c2f20d1c5ea" #pa.2dc483e73851c137.15d94e61e0b377f1
tokentype = "client_cert"
tokenpolicies = ["ubdlza.storagehandler"]
tokeninterval = "48h"
tokenttl = "96h"
certtype = "client_cert"
dnss = []
uris = ["grpc:miniresolverproto.MiniResolver", "grpc:ubdlza.handlerproto.StorageHandlerHandlerService"]
ips = []
certinterval = "24h"
certttl = "48h"
ca = ["certs/minivault.ca.pem"]
usesystempool = false

[log]
level = "debug"
[log.stash]
logstashhost="localhost"
#logstashhost="ub-log.ub.unibas.ch"
logstashport=5047
logstashtracelevel="ERROR"
namespace="dlza_sh"
dataset=""
#dataset="almasync.alma2elastic"
[log.stash.tls]
type="file"
interval="1h"
[log.stash.tls.file]
ca=["certs/ca-t.crt"]
cert="certs/ub-log.ub.unibas-t.ch.cert.pem"
key="certs/ub-log.ub.unibas-t.ch.key.pem"

[s3tempstorage]
type = "s3"
name = "temp_switch_ch"
key = "AKIAFEDBDB2704C24D21"
secret = ""
bucket = "ub-test-dlza-temporary"
apiurlvalue = "https://vip-ecs-ub.storage.p.unibas.ch/"
url = "vip-ecs-ub.storage.p.unibas.ch"
uploadfolder = "vfs:/temp_switch_ch"
capem = "ignore"
debug = false

[tusserver]
addr = "localhost:8085"
